"""Block 3: Execution Engine using LangGraph.

This module orchestrates tool execution based on the plan from Block 2.
"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass
from enum import Enum
import time
from src.utils.logger import get_logger


class ExecutionStatus(Enum):
    """Status of execution."""
    SUCCESS = "success"
    FAILED = "failed"
    RETRY = "retry"


@dataclass
class ToolResult:
    """Result from a tool execution."""
    tool_name: str
    success: bool
    result: Any
    error: Optional[str] = None
    execution_time: float = 0.0


class ExecutionEngine:
    """Execution engine that runs plans with tools."""
    
    def __init__(self, config):
        """Initialize execution engine.
        
        Args:
            config: Configuration object with Block 3 settings.
        """
        self.config = config.block3
        self.logger = get_logger()
        
        self.max_retries = self.config.max_retries
        self.retry_delay = self.config.retry_delay
        self.timeout = self.config.timeout
        
        # Initialize tools (simplified for now)
        self.tools = self._initialize_tools()
        
        self.logger.logger.info(
            f"Initialized ExecutionEngine with {len(self.tools)} tools"
        )
    
    def _initialize_tools(self) -> Dict[str, Any]:
        """Initialize available tools."""
        # Import tools dynamically
        try:
            from block3_execution.tools.create_knowledge_graph import knowledge_graph_tool
            from src.block3_execution.tools.sentiment_analyzer import sentiment_analyzer_tool
            from src.block3_execution.tools.summarizer import summarizer_tool
            from src.block3_execution.tools.news_aggregator import news_aggregator_tool
            from src.block3_execution.tools.google_search import google_search_tool

            return {
                'knowledge_graph': knowledge_graph_tool,
                'sentiment_analyzer': sentiment_analyzer_tool,
                'summarizer': summarizer_tool,
                'news_aggregator': news_aggregator_tool,
                'google_search': google_search_tool,
            }
        except ImportError as e:
            self.logger.logger.warning(f"Could not import tools: {e}. Using mock tools.")
            # Fallback to mock tools if import fails
            return {
                'knowledge_graph': self._mock_knowledge_graph,
                'sentiment_analyzer': self._mock_sentiment_analyzer,
                'summarizer': self._mock_summarizer,
                'news_aggregator': self._mock_news_aggregator,
                'google_search': self._mock_google_search,
            }
    
    def execute_plan(
        self,
        plan: Dict[str, Any],
        query: str,
        context: Dict = None
    ) -> Dict[str, Any]:
        """Execute a plan generated by the planner.
        
        Args:
            plan: Structured plan from Block 2.
            query: Original user query.
            context: Optional execution context.
            
        Returns:
            Dictionary with:
                - final_answer: Final synthesized answer
                - tool_results: Results from each tool
                - status: Execution status
                - observations: List of observations
        """
        self.logger.log_execution_start()
        
        tool_results = []
        observations = []
        
        steps = plan.get('steps', [])
        
        for i, step in enumerate(steps, 1):
            self.logger.logger.info(f"Executing step {i}/{len(steps)}")
            
            tool_name = step.get('tool')
            if not tool_name or tool_name not in self.tools:
                self.logger.logger.warning(
                    f"Tool '{tool_name}' not found, skipping step"
                )
                continue
            
            # Execute tool with retry logic
            result = self._execute_tool_with_retry(
                tool_name=tool_name,
                args={'query': query, 'context': context, 'step': step}
            )
            
            tool_results.append(result)
            
            if result.success:
                observations.append(f"Step {i}: {result.result}")
            else:
                observations.append(f"Step {i}: FAILED - {result.error}")
                # For now, continue execution even on failure
                # In full implementation, trigger re-planning here
        
        # Synthesize final answer from observations
        final_answer = self._synthesize_answer(query, observations)
        
        self.logger.log_execution_complete(final_answer)
        
        return {
            'final_answer': final_answer,
            'tool_results': tool_results,
            'status': ExecutionStatus.SUCCESS.value,
            'observations': observations
        }
    
    def _execute_tool_with_retry(
        self,
        tool_name: str,
        args: Dict
    ) -> ToolResult:
        """Execute tool with retry logic.
        
        Args:
            tool_name: Name of tool to execute.
            args: Arguments for tool.
            
        Returns:
            ToolResult object.
        """
        tool_func = self.tools[tool_name]
        
        for attempt in range(self.max_retries):
            try:
                self.logger.log_tool_call(tool_name, args)
                
                start_time = time.time()
                result = tool_func(**args)
                execution_time = time.time() - start_time
                
                tool_result = ToolResult(
                    tool_name=tool_name,
                    success=True,
                    result=result,
                    execution_time=execution_time
                )
                
                self.logger.log_tool_result(tool_name, True, result)
                
                return tool_result
                
            except Exception as e:
                self.logger.logger.warning(
                    f"Tool {tool_name} failed (attempt {attempt+1}/{self.max_retries}): {e}"
                )
                
                if attempt < self.max_retries - 1:
                    time.sleep(self.retry_delay)
                else:
                    return ToolResult(
                        tool_name=tool_name,
                        success=False,
                        result=None,
                        error=str(e)
                    )
    
    def _synthesize_answer(
        self,
        query: str,
        observations: List[str]
    ) -> str:
        """Synthesize final answer from observations.
        
        Args:
            query: Original query.
            observations: List of observations from tool executions.
            
        Returns:
            Final synthesized answer.
        """
        # Simple synthesis for now
        # In full implementation, use LLM to synthesize
        successful_obs = [obs for obs in observations if "FAILED" not in obs]
        
        if not successful_obs:
            return "I apologize, but I was unable to gather the information needed to answer your query."
        
        answer = f"Based on the available information:\n\n"
        answer += "\n".join(f"- {obs}" for obs in successful_obs)
        
        return answer
    
    # Mock tool implementations
    def _mock_knowledge_graph(self, query: str, **kwargs) -> str:
        """Mock knowledge graph tool."""
        return f"Knowledge graph results for: {query[:50]}..."

    def _mock_sentiment_analyzer(self, query: str, **kwargs) -> str:
        """Mock sentiment analyzer tool."""
        return "Sentiment: Positive (confidence: 0.85)"

    def _mock_summarizer(self, query: str, **kwargs) -> str:
        """Mock summarizer tool."""
        return f"Summary: {query[:100]}..."

    def _mock_news_aggregator(self, query: str, **kwargs) -> str:
        """Mock news aggregator tool."""
        return "Latest news: [Recent articles about the topic]"

    def _mock_google_search(self, query: str, **kwargs) -> str:
        """Mock Google search tool."""
        return f"Google search results for: {query[:50]}..."


def create_execution_engine(config) -> ExecutionEngine:
    """Factory function to create execution engine.
    
    Args:
        config: Configuration object.
        
    Returns:
        ExecutionEngine instance.
    """
    return ExecutionEngine(config)