"""Block 4: Reward Calculation Engine.

This module calculates multi-component rewards for RL training.
"""

from typing import Dict, Any
import os
from openai import OpenAI
from src.utils.logger import get_logger


class RewardCalculator:
    """Calculate rewards for agent performance.
    
    Uses three components:
    1. Correctness: Jaccard similarity with ground truth
    2. Utility: LLM-as-judge score (RLAIF)
    3. Fluency: LLM-as-judge score (RLAIF)
    """
    
    def __init__(self, config):
        """Initialize reward calculator.
        
        Args:
            config: Configuration object with Block 4 settings.
        """
        self.config = config.block4
        self.logger = get_logger()
        
        self.weights = self.config.reward_weights
        
        # Initialize judge LLM for RLAIF
        api_key = os.getenv("OPENAI_API_KEY")
        if api_key:
            self.client = OpenAI(api_key=api_key)
            self.judge_model = self.config.judge_model
        else:
            self.logger.logger.warning("No OpenAI API key, using simplified rewards")
            self.client = None
        
        self.logger.logger.info("Initialized RewardCalculator")
    
    def calculate_reward(
        self,
        query: str,
        agent_plan: Dict,
        agent_answer: str,
        ground_truth_plan: Dict = None,
        ground_truth_answer: str = None
    ) -> Dict[str, float]:
        """Calculate multi-component reward.
        
        Args:
            query: Original query.
            agent_plan: Plan generated by agent.
            agent_answer: Final answer from agent.
            ground_truth_plan: Ideal plan (if available).
            ground_truth_answer: Ideal answer (if available).
            
        Returns:
            Dictionary with reward components and final reward.
        """
        # Calculate each component
        r_correctness = self._calculate_correctness(
            agent_plan, ground_truth_plan
        ) if ground_truth_plan else 0.5
        
        r_utility = self._calculate_utility(
            query, agent_answer
        )
        
        r_fluency = self._calculate_fluency(
            agent_answer
        )
        
        # Weighted combination
        r_final = (
            self.weights['correctness'] * r_correctness +
            self.weights['utility'] * r_utility +
            self.weights['fluency'] * r_fluency
        )
        
        rewards = {
            'r_correctness': r_correctness,
            'r_utility': r_utility,
            'r_fluency': r_fluency,
            'r_final': r_final
        }
        
        self.logger.log_reward(rewards)
        
        return rewards
    
    def _calculate_correctness(
        self,
        agent_plan: Dict,
        ground_truth_plan: Dict
    ) -> float:
        """Calculate correctness using Jaccard similarity.
        
        Args:
            agent_plan: Agent's plan.
            ground_truth_plan: Ground truth plan.
            
        Returns:
            Correctness score (0-1).
        """
        if not ground_truth_plan:
            return 0.5  # Default
        
        # Extract tool names from plans
        agent_tools = set()
        for step in agent_plan.get('steps', []):
            if step.get('tool'):
                agent_tools.add(step['tool'])
        
        truth_tools = set()
        for step in ground_truth_plan.get('steps', []):
            if step.get('tool'):
                truth_tools.add(step['tool'])
        
        # Jaccard similarity
        if not agent_tools and not truth_tools:
            return 1.0
        
        if not agent_tools or not truth_tools:
            return 0.0
        
        intersection = len(agent_tools & truth_tools)
        union = len(agent_tools | truth_tools)
        
        return intersection / union if union > 0 else 0.0
    
    def _calculate_utility(self, query: str, answer: str) -> float:
        """Calculate utility using LLM-as-judge (RLAIF).
        
        Args:
            query: User query.
            answer: Agent's answer.
            
        Returns:
            Utility score (0-1).
        """
        if not self.client:
            return 0.7  # Default
        
        try:
            prompt = f"""Rate the helpfulness and utility of this answer on a scale of 1-10.

Query: {query}

Answer: {answer}

Consider:
- Does it answer the question?
- Is it helpful and informative?
- Does it provide useful insights?

Respond with ONLY a number from 1-10."""
            
            response = self.client.chat.completions.create(
                model=self.judge_model,
                messages=[
                    {"role": "system", "content": "You are an objective judge rating AI responses."},
                    {"role": "user", "content": prompt}
                ],
                temperature=self.config.judge_temperature,
                max_tokens=10
            )
            
            score_text = response.choices[0].message.content.strip()
            score = float(score_text) / 10.0  # Normalize to 0-1
            
            return max(0.0, min(1.0, score))
            
        except Exception as e:
            self.logger.logger.warning(f"Error calculating utility: {e}")
            return 0.7
    
    def _calculate_fluency(self, answer: str) -> float:
        """Calculate fluency using LLM-as-judge (RLAIF).
        
        Args:
            answer: Agent's answer.
            
        Returns:
            Fluency score (0-1).
        """
        if not self.client:
            return 0.8  # Default
        
        try:
            prompt = f"""Rate the linguistic quality and fluency of this text on a scale of 1-10.

Text: {answer}

Consider:
- Grammar and spelling
- Clarity and coherence
- Natural flow
- Professional tone

Respond with ONLY a number from 1-10."""
            
            response = self.client.chat.completions.create(
                model=self.judge_model,
                messages=[
                    {"role": "system", "content": "You are an objective judge rating text quality."},
                    {"role": "user", "content": prompt}
                ],
                temperature=self.config.judge_temperature,
                max_tokens=10
            )
            
            score_text = response.choices[0].message.content.strip()
            score = float(score_text) / 10.0  # Normalize to 0-1
            
            return max(0.0, min(1.0, score))
            
        except Exception as e:
            self.logger.logger.warning(f"Error calculating fluency: {e}")
            return 0.8


def create_reward_calculator(config) -> RewardCalculator:
    """Factory function to create reward calculator.
    
    Args:
        config: Configuration object.
        
    Returns:
        RewardCalculator instance.
    """
    return RewardCalculator(config)